export const language =  {
    english: {
        clickToCopy: 'Click to Copy Link',
        deletePrompt: 'Are you sure you want to delete?',
        block: 'Block',
        addEvent: 'Add Event',
        event: 'Event',
        eventTitle: 'Event Title',
        linkToShare: 'Link to share',
        selectLanguage: 'Select language',
        welcome: 'Welcome',
        dailyStartTime: 'Daily Start Time',
        dailyEndTime: 'Daily End Time',
        eventsCannotChange: 'Events cannot be changed',
        hoursBeforeTimeSlot: 'hours before scheduled time slot',
        splitCalendarBy: 'Split calendar by',
        minutes: 'minutes',
        scheduleCanBeBooked: 'Schedule can be booked',
        weeksInAdvance: 'weeks in advance',
        currentSchedules: 'Current schedules',
        adminSettings: 'Admin Settings',
        signOut: 'Sign Out',
        ok: 'Ok',
        cancel: 'Cancel',
        confirm: 'Confirm',
        alertDetails: 'Alert Details',
        phoneNumber: 'phone number',
        phone: 'phone',
        name: 'name',
        title: 'title',
        time: 'time',
        email: 'email',
        sureDelete: 'Are you sure you want to delete?',
        appointmentChanged: 'Appointment cannot be changed',
        cannotBookHere: 'cannot book here',
        hoursBefore: 'hours before',
        no: 'No',
        yes: 'Yes'
    },
    spanish: {
        clickToCopy: 'Haga Clic Para Copiar El Enlace',
        deletePrompt: 'estas seguro que quieres borrarlo?',
        block: 'Bloquear',
        addEvent: 'Añadir Evento',
        selectLanguage: 'seleccione el idioma',
        event: 'Evento',
        eventTitle: 'Titulo del evento',
        linkToShare: 'Compartir',
        welcome: 'Bienvenido',
        dailyStartTime: 'Hora de inicio diaria',
        dailyEndTime: 'Hora de finalización diaria',
        eventsCannotChange: 'Eventos no pueden ser cambiados',
        hoursBeforeTimeSlot: 'Horas antes del horario programado',
        splitCalendarBy: 'Dividir calendario por',
        minutes: 'Minutos',
        scheduleCanBeBooked: 'Horario se puede reservar',
        weeksInAdvance: 'Semanas de antelación',
        currentSchedules: 'Horarios actuales',
        adminSettings: 'Configuración de Administrador',
        signOut: 'Cerrar sesión',
        ok: 'Listo',
        cancel: 'Cancelar',
        confirm: 'Confirmar',
        alertDetails: 'Detalles de alerta',
        phoneNumber: 'Numero de telefono',
        phone: 'Numero',
        name: 'Nombre',
        title: 'Titulo',
        time: 'Tiempo',
        email: 'email',
        sureDelete: '¿Estás seguro de que quieres eliminar?',
        appointmentChanged: 'Cita no puede ser cambiada',
        cannotBookHere: 'No se puede reservar aquí',
        hoursBefore: 'Horas antes',
        no: 'No',
        yes: 'Si'
    }
}